version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logistica_service
    ports:
      - "3001:3001" # Mapea el puerto 3001 del host al 3001 del contenedor
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  redis:
    image: "redis:7"
    container_name: redis-server
    ports:
      - "6379:6379" # Puerto Redis
    command: ["redis-server", "--appendonly", "yes"] # Configuración para persistencia